//
// Created by pylinskyi.k on 13.12.2023.
//

#ifndef PELAGEIA_IMMERSIVE_SPRITEANIMATIONCOMPONENT_H
#define PELAGEIA_IMMERSIVE_SPRITEANIMATIONCOMPONENT_H

#endif  // PELAGEIA_IMMERSIVE_SPRITEANIMATIONCOMPONENT_H
