//
// Created by pylinskyi.k on 13.12.2023.
//

#ifndef PELAGEIA_IMMERSIVE_GAMEMAPENTITY_H
#define PELAGEIA_IMMERSIVE_GAMEMAPENTITY_H

class GameMapEntity {

};

#endif  // PELAGEIA_IMMERSIVE_GAMEMAPENTITY_H
